### PR TITLE
🐛 Fix WidgetsBinding.instance log spam

### LINKED ISSUE #203: WidgetBinding analyzer noise for Flutter >=3
Change introduced in this commit: 
https://github.com/DataDog/dd-sdk-flutter/commit/a6a66306011d20566c258d39203659feca871546

results in noisy analyzer when running from CLI:

```
./../../../.pub-cache/hosted/pub.dartlang.org/datadog_flutter_plugin-1.0.0-rc.2/lib/src/rum/rum_long_task_observer.dart:44:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../Utils/flutterSdk/flutterStable/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addObserver(this);
```

This makes tests output hard to read.

### PR DESCRIPTION
**Pull request by fuzzybinary**
### What and why?

Because WidgetsBinding.instance is optional in Flutter 2.x, we have to use `?.` to access it. However, in Flutter 3,  WidgetsBinding is now non-optional, and Flutter will give you a warning that your use of ?. is unnecessary, even when you put an `// ignore:` comment above it.

### How?

I added a method `ambiguate` that makes WidgetsBinding.instance back into to optional, which can then be used safely with `?.`. This is actually the recommend method from Flutter's release note on Flutter 3.0: https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#your-code

Fixes #203

### Review checklist

- [ ] This pull request has appropriate unit and / or integration tests 
- [x] This pull request references a Github or JIRA issue

### CI Configuration (optional)
- [ ] Run unit tests
- [ ] Run integration tests

### CODE REVIEW

File: packages/datadog_flutter_plugin/lib/src/helpers.dart [hunk 1]
```diff
@@ -142,3 +142,9 @@ InvalidAttributeInfo? findInvalidAttribute(Map<String, Object?> attributes,
     [String parentPropertyName = '']) {
   return _checkInvalidValue(attributes, parentPropertyName);
 }
+
+/// This allows a value of type T or T? to be treated as a value of type T?.
+///
+/// We use this so that APIs that have become non-nullable can still be used
+/// with `!` and `?` to support older versions of FLutter.
```
Comment (0xnm) [inline packages/datadog_flutter_plugin/lib/src/helpers.dart:149]:
```suggestion
/// with `!` and `?` to support older versions of Flutter.
```

**Review by 0xnm — APPROVED** [review]

**Review by xgouchet — APPROVED** [review]
