### PR TITLE
Don't attempt to reinitialize Datadog on hot-reload

### LINKED ISSUE #141: SDK is already initialised
**Describe what happened**
An error message "Datadog SDK usage error: SDK is already initialized." appears when the app is restarted following hot reload.  Whilst this can be ignored, it seems to me that it would be better suppressed given that it is such a commonality.

```
flutter: 🔥 Datadog SDK usage error: SDK is already initialized.
flutter: 🔥 Datadog SDK usage error: The `Tracer` instance was already created. Use existing `Global.sharedTracer` instead of initializing the `Tracer` another time.
flutter: 🔥 Datadog SDK usage error: The `RUMMonitor` instance was already created. Use existing `Global.rum` instead of initializing the `RUMMonitor` another time.
```

**Additional context**
 - Dart/Flutter version: Dart 2.17.1 / Flutter 3.0
 - Datadog SDK version: datadog_flutter_plugin: ^1.0.0-beta.2

### PR DESCRIPTION
**Pull request by fuzzybinary**
### What and why?

Because hot reload / hot restart can recall `main`, you can get multiple requests to initialize Datadog, and the warning we spit to the console can get annoying. This removes that warning if your initialization hasn't changed.

If your initialization has changed, this shows a warning.

This fixes #141 

### Review checklist

- [x] This pull request has appropriate unit and / or integration tests 
- [x] This pull request references a Github or JIRA issue

### CI Configuration (optional)
- [x] Run unit tests
- [x] Run integration tests

### CODE REVIEW

File: packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogSdkPlugin.kt [hunk 1]
```diff
@@ -149,3 +157,9 @@ class DatadogSdkPlugin : FlutterPlugin, MethodCallHandler {
         rumPlugin = null
     }
 }
+
+internal const val DATADOG_FLUTTER_TAG = "DatadogFlutter"
+
+internal const val MESSAGE_INVALID_REINITIALIZATION =
+    "🔥 Reinitialziing the DatadogSDK with different options, even after a hot restart, is not" +
+        "supported. Cold restart your application to change your current configuation."
```
Comment (0xnm) [inline packages/datadog_flutter_plugin/android/src/main/kotlin/com/datadoghq/flutter/DatadogSdkPlugin.kt:165]:
```suggestion
        " supported. Cold restart your application to change your current configuation."
```

File: packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt [hunk 2]
```diff
@@ -157,6 +162,87 @@ class DatadogSdkPluginTest {
...
+                    "nativeCrashReportEnabled" to true,
+                    "loggingConfiguration" to null
+                )
+            )
+        )
+        val mockResultB = mock<MethodChannel.Result>()
+        plugin.onMethodCall(methodCallB, mockResultB)
+
+        // THEN
+        io.mockk.verify(exactly = 1) { Log.e(any(), match { it.contains("🔥") }) }
```
Comment (0xnm) [inline packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt:243]: I think we can remove `any()` and `match()` calls here and reference directly tag and message, because they are `internal` and should be available.

File: packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/ReflectUtils.kt [hunk 3]
```diff
@@ -58,6 +58,7 @@ private fun <T : Any> T.getDeclaredMethodRecursively(
         val lookingInClass = classesToSearch.removeAt(0)
         classesSearched.add(lookingInClass)
         method = try {
+            var methods = lookingInClass.declaredMethods
```
Comment (0xnm) [inline packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/ReflectUtils.kt:61]: is not used it seems

File: packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt [hunk 4]
```diff
@@ -157,6 +162,87 @@ class DatadogSdkPluginTest {
         verify(mockResult).success(null)
     }
 
+    @Test
+    fun `M not issue warning W initialize called with same configuration`(
+        forge: Forge
+    ) {
+        // GIVEN
+        mockkStatic(Log::class)
```
Comment (0xnm) [inline packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt:170]: personally I'm not big fan of static mocks, because to mock static bytecode modification is needed (this is what `mockk` is doing under the hood, probably).

maybe we can do non-static wrapper around `Log`?

Anyway, is not a blocker for me, just a personal opinion :)

File: packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt [hunk 5]
```diff
@@ -30,11 +30,15 @@ import io.flutter.embedding.engine.plugins.FlutterPlugin
...
 import io.flutter.plugin.common.MethodChannel
+import io.mockk.mockkStatic
 import io.opentracing.util.GlobalTracer
 import org.junit.jupiter.api.AfterEach
 import org.junit.jupiter.api.BeforeEach
 import org.junit.jupiter.api.Test
 import org.junit.jupiter.api.extension.ExtendWith
+import org.mockito.MockedStatic
+import org.mockito.Mockito
+import org.mockito.Mockito.mockStatic
```
Comment (0xnm) [inline packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt:41]: seems like those 3 are not used. And if Mockito has `mockStatic`, then why do we bring `mockk`?

File: packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/ReflectUtils.kt (hunk 3 above)
Comment (fuzzybinary) [reply packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/ReflectUtils.kt:61]: Ah, thanks. I was trying to figure out how to call something via reflection and forgot to remove this.

File: packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt (hunk 5 above)
Comment (fuzzybinary) [reply packages/datadog_flutter_plugin/android/src/test/kotlin/com/datadoghq/flutter/DatadogSdkPluginTest.kt:41]: Ugh, yeah (I'm surprised ktlint and detekt didn't call this out....).

It's because Mockito's mockStatic doesn't work with Android. I don't know the particulars but when you try to use it throws an exception. mockk's version works with Android (and to be honest, I kinda like mockk better... I might switch everything over at some point).
